name = "lapce-emmet-ls"
version = "0.1.1"
author = "Zach Hornung"
display-name = "lapce-emmet-ls"
description = "Emmet for Lapce"
wasm = "bin/lapce-emmet-ls.wasm"
icon = "emmet-logo.svg"
repository = "https://github.com/zachhornung/lapce-emmet-ls"

[activation]
language = [
  "html", 
  "javascriptreact", 
  "typescriptreact", 
  "css",
  "less",
  "sass",
  "scss",
  "svelte",
  "pug",
  "vue"
]
workspace-contains = [
  "**/*.html",
  "**/*.jsx",
  "**/*.tsx",
  "**/*.css",
  "**/*.less",
  "**/*.sass",
  "**/*.scss",
  "**/*.svelte",
  "**/*.pug",
  "**/*.vue",
]

[config."lsp.serverPath"]
default = ""
description = "Path to emmet-ls"

[config."lsp.serverArgs"]
default = ["--stdio"]
description = "Arguments to pass to emmet-ls. `--stdio` is default and required f"

# [config."lspSettingArray"]
# default = []
# description = ""

# [config."lspSettingString"]
# default = ""
# description = ""

# [config."lspSettingBool"]
# default = false
# description = ""
